name: resq360
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  another_flushbar: ^1.12.32
  app_tracking_transparency: ^2.0.6+1
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.1.0
  dio: ^5.9.0
  dropdown_button2: ^2.3.9
  equatable: ^2.0.7
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.1
  geocoding: ^4.0.0
  go_router: 15.0.0
  google_fonts: ^6.3.1
  http: ^1.5.0
  http_parser: ^4.1.2
  image_cropper: ^10.0.0+1
  image_picker: ^1.2.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  slang_flutter: 3.31.0
  upgrader: ^12.1.0
  url_launcher: ^6.3.2
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: 2.8.0
  integration_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.1
  slang_build_runner: 3.31.0
  very_good_analysis: ^10.0.0

flutter_native_splash:
  android: true
  ios: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: center
  background_image: assets/logo/splash.png
  background_image_dark: assets/logo/splash.png
  android_12:
    color: "#004B4D"
    color_dark: "#004B4D"
    image: assets/logo/logo.png
    image_dark: assets/logo/logo.png

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
