name: resq360
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  another_flushbar: ^1.12.32
  app_tracking_transparency: ^2.0.6+1
  badges: ^3.1.2
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.1.0
  dio: ^5.9.0
  dropdown_button2: ^2.3.9
  equatable: ^2.0.7
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  flutter_countdown_timer: ^4.1.0
  flutter_local_notifications: ^19.4.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.1
  geocoding: ^4.0.0
  # go_router: 15.0.0
  geolocator: ^14.0.1
  google_fonts: ^6.3.1
  google_sign_in: ^7.2.0
  http: ^1.5.0
  http_parser: ^4.1.2
  image_cropper: ^10.0.0+1
  image_picker: ^1.2.0
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  pin_code_text_field: ^1.8.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  sign_in_with_apple: ^7.0.1
  slang_flutter: 3.31.0
  upgrader: ^12.1.0
  url_launcher: ^6.3.2
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: 2.8.0
  integration_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.1
  slang_build_runner: 3.31.0
  very_good_analysis: ^10.0.0

flutter_native_splash:
  android: true
  ios: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: center
  background_image: assets/logo/splash_2.png
  background_image_dark: assets/logo/splash_2.png
  android_12:
    color: "#FFFFFF"
    color_dark: "#FFFFFF"
    image: assets/logo/logo.png
    image_dark: assets/logo/logo.png

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/logo/
    - assets/navigation/

  fonts:
    - family: "inter"
      fonts:
        - asset: fonts/Inter/Inter-Thin-BETA.otf
          weight: 100
        - asset: fonts/Inter/Inter-ThinItalic-BETA.otf
          weight: 100
          style: italic
        - asset: fonts/Inter/Inter-ExtraLight-BETA.otf
          weight: 200
        - asset: fonts/Inter/Inter-ExtraLightItalic-BETA.otf
          weight: 200
          style: italic
        - asset: fonts/Inter/Inter-Light-BETA.otf
          weight: 300
        - asset: fonts/Inter/Inter-LightItalic-BETA.otf
          weight: 300
          style: italic
        - asset: fonts/Inter/Inter-Regular.otf
          weight: 400
        - asset: fonts/Inter/Inter-Italic.otf
          weight: 400
          style: italic
        - asset: fonts/Inter/Inter-Medium.otf
          weight: 500
        - asset: fonts/Inter/Inter-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/Inter/Inter-SemiBold.otf
          weight: 600
        - asset: fonts/Inter/Inter-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/Inter/Inter-Bold.otf
          weight: 700
        - asset: fonts/Inter/Inter-BoldItalic.otf
          weight: 700
          style: italic
        - asset: fonts/Inter/Inter-ExtraBold.otf
          weight: 800
        - asset: fonts/Inter/Inter-ExtraBoldItalic.otf
          weight: 800
          style: italic
        - asset: fonts/Inter/Inter-Black.otf
          weight: 900
        - asset: fonts/Inter/Inter-BlackItalic.otf
          weight: 900
          style: italic

    - family: urbanist
      fonts:
        - asset: fonts/urbanist/Urbanist-Thin.ttf
          weight: 100
        - asset: fonts/urbanist/Urbanist-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/urbanist/Urbanist-ExtraLight.ttf
          weight: 200
        - asset: fonts/urbanist/Urbanist-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/urbanist/Urbanist-Light.ttf
          weight: 300
        - asset: fonts/urbanist/Urbanist-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: fonts/urbanist/Urbanist-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: fonts/urbanist/Urbanist-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: fonts/urbanist/Urbanist-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/urbanist/Urbanist-Bold.ttf
          weight: 700
        - asset: fonts/urbanist/Urbanist-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/urbanist/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: fonts/urbanist/Urbanist-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/urbanist/Urbanist-Black.ttf
          weight: 900
        - asset: fonts/urbanist/Urbanist-BlackItalic.ttf
          weight: 900
          style: italic
